openapi: 3.0.3
info:
  title: Easyapp API
  version: 1.0.0
  description: API documentation for easyapp
servers:
  - url: /
paths:
  /api/register/:
    $ref: ./endpoints/register.yml
  /api/login/:
    $ref: ./endpoints/login.yml
  /api/profile/:
    $ref: ./endpoints/profile.yml
  /api/messages/:
    $ref: ./endpoints/messages.yml
components:
  schemas:
    Member:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
          format: email
        display_name:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - email
        - display_name
        - created_at
        - updated_at
    ChatMessage:
      type: object
      properties:
        id:
          type: integer
        member:
          $ref: '#/components/schemas/Member'
        text:
          type: string
          maxLength: 1000
        created_at:
          type: string
          format: date-time
      required:
        - id
        - member
        - text
        - created_at
    TokenResponse:
      type: object
      properties:
        token:
          type: string
          description: Token string to be sent as "Authorization: Token <key>"
        member:
          $ref: '#/components/schemas/Member'
      required:
        - token
        - member
  securitySchemes:
    TokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Use format "Token <key>"
